### PR TITLE
Fixed a missing dollar on the measurment variable.

### PR DESCRIPTION
**Pull request by Wipster**

### CODE REVIEW

**Comment by beberlei** [comment]
@Wipster thank you, stupid mistake. However `Tideways.php` is not used anymore in Tideways since PHP extension version 5 was released 1,5 years ago. how did you come across this?

**Comment by Wipster** [comment]
@beberlei Thanks for merging. I'm maintaining a very old application using PHP 5.5 :confused:

**Comment by beberlei** [comment]
@Wipster our PHP extension version 5 has support for PHP 5.5 - Can you write an e-mail to support@tideways.com? I can help you from there.

**Comment by Wipster** [comment]
@beberlei Ah thanks for the info, didn't know that. I'm going to figure it out by myself and come back to your offer when i'm stuck!

**Pull request merged**
